{
 "title": "Fee",
 "time": { "from": "2024-06-05T03:36:21.000Z", "to": "2024-06-05T03:46:05.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"Batch\" ORDER BY batch DESC "
    }
   ]
  },
  {
   "title": "TX in Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"createdAt\", \"totalTx\" FROM \"Batch\" ORDER BY \"createdAt\" DESC "
    }
   ]
  },
  {
   "title": "Block in Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "L2 Fee Collected(Based on Batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"createdAt\", \"l2FeeCollected\" FROM \"Batch\" ORDER BY \"createdAt\" DESC "
    }
   ]
  },
  {
   "title": "L1 Fee Spend(Based on Batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"createdAt\", \"l1CommitFee\", \"l1ExecuteFee\", \"l1ProveFee\" FROM \"Batch\" ORDER BY \"createdAt\" "
    }
   ]
  },
  {
   "title": "L1 Fee Spent vs L2 Fee Collected",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "($A + $B + $C) / 1000000000000000000",
     "type": "math"
    },
    {
     "rawSql": "SELECT batch, \"createdAt\" FROM \"Batch\" "
    },
    {
     "expression": "$L2FeeWEI / 1000000000000000000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Fee Collected(L2 collected - L1 spent)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "downsampler": "mean",
     "expression": "$L2FeeCollected - $L1FeeSpent",
     "type": "math",
     "upsampler": "fillna",
     "window": "1m"
    }
   ]
  },
  {
   "title": "L1 Fee Spend(Based on Batch)",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT batch, \"createdAt\" FROM \"Batch\" "
    },
    {
     "downsampler": "mean",
     "expression": "$L2FeeCollected - $L1FeeSpent",
     "type": "math",
     "upsampler": "fillna",
     "window": "1m"
    }
   ]
  }
 ]
}